import type { DisplayTurn, TurnResult } from '../api/types'
import { actionName, decisions, formatMs, formatValue, languages, queues, scenarioName, slotName, slotPrompt } from '../data/labels'
import { Icon } from './Icon'

function Candidates({ items }: { items: TurnResult['scenarios'] }) {
  return <div className="candidates">{items.map((item, index) => <div className="candidate" key={`${item.scenario_id}-${index}`}><div className="candidate-title"><span className="scenario-id">{item.scenario_id}</span><span>{scenarioName(item.scenario_id)}</span><strong>{Math.round(item.confidence * 100)}%</strong></div><meter min="0" max="1" value={item.confidence} aria-label={`Уверенность ${item.scenario_id}`} /></div>)}</div>
}
export function TracePanel({ turn }: { turn: DisplayTurn | null }) {
  const result = turn?.result
  return <aside className="trace panel" aria-label="Трассировка">
    <div className="panel-header"><div className="header-title"><Icon name="trace"/><h2>Логика ответа</h2></div><span className="badge">{result ? `Ход ${result.turn}` : 'Трассировка'}</span></div>
    {!result ? <div className="trace-empty"><div className="empty-route"><span/><span/><span/></div><h3>Каждое решение — на виду</h3><p>Выберите реплику в диалоге, чтобы увидеть сценарий, аргументы и время ответа.</p><div className="trace-outline"><span>Сценарий</span><span>Обоснование</span><span>Параметры</span><span>Задержки</span></div></div> : <div className="trace-content">
      <div className="trace-meta"><span className={`badge ${result.mode === 'mock' ? 'amber' : 'green'}`}>{result.mode === 'mock' ? 'Mock · пример' : 'Live · ответ сервера'}</span><span>{languages[result.language]} → {languages[result.response_language]}</span></div>
      <section className="trace-section"><div className="section-title"><h3>Выбранные сценарии</h3><span className="small muted">Уверенность{result.mode === 'mock' ? ' · условная' : ''}</span></div><Candidates items={result.scenarios}/><p className="reason">{result.reason || 'Обоснование не передано.'}</p><div className="decision-row"><span className="badge">{decisions[result.decision]}</span>{result.is_continuation && <span className="small muted">Продолжение темы</span>}</div></section>
      {result.pending_confirmation && <section className="callout confirm"><h3>Ожидается подтверждение</h3><p>{result.pending_confirmation.summary}</p><p className="small">Ответьте следующей репликой. Пока показан только предпросмотр.</p><details><summary>Параметры подтверждения</summary><pre>{JSON.stringify(result.pending_confirmation.parameters, null, 2)}</pre><code>{result.pending_confirmation.confirmation_id}</code></details></section>}
      {result.handoff && <section className="callout handoff"><Icon name="headphones"/><h3>Передача оператору — симуляция</h3><strong>{queues[result.handoff.queue] ?? result.handoff.queue}</strong><p>{result.handoff.summary}</p><code>{result.handoff.queue}</code></section>}
      <section className="trace-section"><h3>Контекст разговора</h3><dl className="context-list"><div><dt>Сейчас</dt><dd>{result.active_scenario ? scenarioName(result.active_scenario) : 'Нет активного сценария'}</dd></div><div><dt>Далее</dt><dd>{result.queued_scenarios.length ? result.queued_scenarios.map(scenarioName).join(' → ') : 'Очередь пуста'}</dd></div></dl></section>
      <section className="trace-section"><h3>Параметры</h3>{Object.keys(result.slots).length ? <dl className="slot-list">{Object.entries(result.slots).map(([name, value]) => <div key={name}><dt title={name}>{slotName(name)}</dt><dd>{formatValue(value)}</dd></div>)}</dl> : <p className="small muted">Параметры ещё не получены.</p>}{result.missing_slots.length > 0 && <div className="missing"><span className="small">Нужно уточнить</span><div className="chips">{result.missing_slots.map(name => <span className="badge amber" key={name} title={slotPrompt(name)}>{slotName(name)}</span>)}</div></div>}</section>
      <section className="trace-section"><h3>Действия</h3>{!result.actions.length && <p className="small muted">Действия не запускались.</p>}{result.actions.map((action, index) => <details className="action" key={`${action.name}-${index}`}><summary><span>{actionName(action.name)}</span><span className={`badge ${action.status === 'error' ? 'red' : action.mode === 'preview' ? 'amber' : 'green'}`}>{action.status === 'error' ? 'Ошибка' : action.mode === 'preview' ? 'Предпросмотр' : 'Выполнено'}</span></summary><p className="small muted">{action.name} · {action.mode}:{action.status}</p><pre>{JSON.stringify(action.status === 'ok' ? action.result : action.error, null, 2)}</pre></details>)}</section>
      <section className="trace-section"><h3>Альтернативы</h3>{result.alternatives.length ? <Candidates items={result.alternatives}/> : <p className="small muted">Альтернативы не предложены.</p>}</section>
      <section className="trace-section"><h3>Задержки</h3><dl className="latency-grid">{([['stt', 'Распознавание речи'], ['triage', 'Первичный разбор'], ['router', 'Выбор сценария'], ['response', 'Подготовка ответа'], ['tts_first_audio', 'Первые аудиоданные TTS']] as const).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{formatMs(result.latency_ms[key])}</dd></div>)}<div className="latency-total"><dt>Обработка на сервере</dt><dd>{formatMs(result.server_processing_ms)}</dd></div><div className="latency-total"><dt>От конца речи до ответа</dt><dd>не измерено</dd></div></dl><p className="small muted">LiveKit передаёт непрерывный аудиотрек. Без отдельного замера конца речи и начала каждого ответа сквозная задержка неизвестна. Текстовый резерв не озвучивается.</p></section>
      {result.warnings.length > 0 && <section className="trace-section"><h3>Замечания</h3>{result.warnings.map((warning, index) => <p className="warning-note" key={index}>{warning.message}</p>)}</section>}
      <details className="technical"><summary>Идентификаторы и JSON ответа</summary><p>turn_id: <code>{result.turn_id}</code></p><p>request_id: <code>{result.request_id}</code></p><pre>{JSON.stringify(result, null, 2)}</pre></details>
    </div>}
  </aside>
}
